shutdown_costmaps: false

obstacles_layer:
  enabled: true
  combination_method: 1
  footprint_clearing_enabled: true
  track_unknown_space: false
  obstacle_range: 3
  raytrace_range: 3.5

  inflation_radius: 0.3
  # update_frequency: 3.0

  #width: 5.0
  #height: 5.0
  resolution: 0.15
  observation_sources: scan point_cloud

  scan: 
    data_type: LaserScan
    topic: /scan
    marking: true
    clearing: true
    inf_is_valid: true
    min_obstacle_height: 0.15
    max_obstacle_height: 1.0

static_layer:
  enabled: true
  #map_topic: /map_for_costmap
  map_topic: /map
  first_map_only: false
  lethal_cost_threshold: 100
  subscribe_to_updates: true
  track_unknown_space: false
  trinary_costmap: false
  unknown_cost_value: -1
  use_maximum: false
# point_cloud: {data_type: PointCloud, topic: /filtered_cloud, marking: true, clearing: true, inf_is_valid: true}
