waypoints:
    - point:
        x: -7.44071
        y: 7.76897
        z: 4.18702e-06
        function: run
    - point:
        x: -9.97204
        y: 5.58839
        z: -3.50278e-07
        function: run_left_3_way_center
    - point:
        x: -10.1602
        y: -1.3721
        z: 1.92205e-06
        function: run
    - point:
        x: -7.47726
        y: -4.18813
        z: -1.65423e-06
        function: run_left_corner_left
    - point:
        x: -2.94933
        y: -4.25886
        z: -1.89265e-06
        function: run
    - point:
        x: -0.227345
        y: -1.37628
        z: -5.81346e-07
        function: run_left_corner_left
    - point:
        x: -0.394537
        y: 2.30184
        z: -1.41581e-06
        function: run_go_3_way_right
    - point:
        x: -0.345637
        y: 5.50435
        z: -9.38974e-07
        function: run
    - point:
        x: -0.494921
        y: 10.3315
        z: -1.89265e-06
        function: run_go_3_way_left
    - point:
        x: -0.290335
        y: 18.9903
        z: -2.13107e-06
        function: run
    - point:
        x: -0.228607
        y: 24.4493
        z: -2.13107e-06
        function: run_go_3_way_left
    - point:
        x: -0.307355
        y: 27.1605
        z: -5.2305e-06
        function: run
    - point:
        x: -2.74363
        y: 29.1105
        z: -3.79999e-06
        function: run_left_corner_left
    - point:
        x: -7.56349
        y: 29.2061
        z: -4.03842e-06
        function: run
    - point:
        x: -9.99399
        y: 27.0014
        z: -1.89265e-06
        function: run_left_3_way_center
    - point:
        x: -9.84327
        y: 24.999
        z: -4.75368e-06
        function: run
    - point:
        x: -10.0096
        y: 21.5426
        z: -3.8e-06
        function: run_go_3_way_left
    - point:
        x: -9.95737
        y: 10.1385
        z: -2.13106e-06
        function: run
    - point:
        x: -7.41761
        y: 7.80013
        z: -3.09209e-06
        function: run_left_3_way_left
    - point:
        x: -3.05288
        y: 7.70501
        z: -1.41581e-06
        function: run
    - point:
        x: -0.303354
        y: 5.49237
        z: -1.89265e-06
        function: run_right_3_way_center
    - point:
        x: -0.416654
        y: 2.48242
        z: -3.8e-06
        function: run
    - point:
        x: -0.265746
        y: -1.36347
        z: -2.13107e-06
        function: run_go_3_way_left
    - point:
        x: -2.90452
        y: -4.26827
        z: -9.04521e-06
        function: run_right_corner_right
    - point:
        x: -7.54279
        y: -4.17058
        z: -7.37627e-06
        function: run
    - point:
        x: -10.1109
        y: -1.41551
        z: -9.0452e-06
        function: run_right_corner_right
    - point:
        x: -10.0099
        y: 5.5503
        z: -6.18417e-06
        function: run
    - point:
        x: -9.94404
        y: 10.1578
        z: 3.64976e-07
        function: run_go_3_way_right
    - point:
        x: -9.989
        y: 21.4608
        z: 4.91537e-07
        function: run
    - point:
        x: -9.89335
        y: 25.0373
        z: 4.91536e-07
        function: run_go_3_way_right
    - point:
        x: -9.92411
        y: 27.0196
        z: 4.30624e-06
        function: run
    - point:
        x: -7.5064
        y: 29.1808
        z: -3.56158e-06
        function: run_right_corner_right
    - point:
        x: -2.7298
        y: 29.1048
        z: 2.53119e-07
        function: run
    - point:
        x: -0.260239
        y: 27.1838
        z: -1.89265e-06
        function: run_right_3_way_center
    - point:
        x: -0.315115
        y: 24.444
        z: -2.23719e-07
        function: run
    - point:
        x: -0.252442
        y: 19.0383
        z: -2.84632e-06
        function: run_go_3_way_right
    - point:
        x: -0.503934
        y: 10.2712
        z: -1.89265e-06
        function: run
    - point:
        x: -2.96919
        y: 7.68379
        z: -2.36949e-06
        function: run_right_3_way_right
    - point:
        x: -7.44121
        y: 7.83477
        z: -3.32316e-06
        function: run
    - point:
        x: -9.9579
        y: 10.1466
        z: 6.03396e-07
        function: run_right_3_way_center
    - point:
        x: -10.0157
        y: 21.4328
        z: -1.89265e-06
        function: run
    - point:
        x: -9.85143
        y: 25.0252
        z: -2.23719e-07
        function: run_go_3_way_right
    - point:
        x: -9.98948
        y: 27.0236
        z: -4.62137e-07
        function: run
    - point:
        x: -7.52068
        y: 29.1966
        z: -4.62139e-07
        function: run_right_corner_right
    - point:
        x: -2.74372
        y: 29.093
        z: -2.36949e-06
        function: run
    - point:
        x: -0.291377
        y: 27.1654
        z: -3.32315e-06
        function: run_right_3_way_center
    - point:
        x: -0.270015
        y: 24.4583
        z: -7.85312e-06
        function: run
    - point:
        x: -0.291364
        y: 19.0342
        z: -9.76046e-06
        function: run_go_3_way_right
    - point:
        x: -0.407087
        y: 10.353
        z: -7.61469e-06
        function: run
    - point:
        x: -0.298859
        y: 5.47578
        z: -7.61469e-06
        function: run_go_3_way_right
    - point:
        x: -0.265104
        y: 2.43624
        z: -8.09153e-06
        function: run
    - point:
        x: -0.147053
        y: -1.39597
        z: -8.56837e-06
        function: run_go_3_way_left
    - point:
        x: -2.8403
        y: -4.29077
        z: -9.99887e-06
        function: run_right_corner_right
    - point:
        x: -7.50053
        y: -4.21663
        z: -9.99888e-06
        function: run
    - point:
        x: -10.113
        y: -1.39841
        z: -9.28361e-06
        function: run_right_corner_right
    - point:
        x: -9.98704
        y: 5.55964
        z: -1.16678e-05
        function: run
    - point:
        x: -7.41673
        y: 7.84525
        z: -5.88696e-07
        function: run_right_3_way_right
    - point:
        x: -2.99487
        y: 7.7278
        z: -4.62137e-07
        function: run
    - point:
        x: -0.482536
        y: 10.3116
        z: 2.16046e-06
        function: run_left_3_way_center
    - point:
        x: -0.251351
        y: 19.0663
        z: 1.46999e-08
        function: run
    - point:
        x: -0.329809
        y: 24.4769
        z: -1.41581e-06
        function: run_go_3_way_left
    - point:
        x: -0.286353
        y: 27.2135
        z: 1.02667e-05
        function: run
    - point:
        x: -2.77214
        y: 29.1439
        z: 6.21358e-06
        function: run_left_corner_left
    - point:
        x: -7.54322
        y: 29.2026
        z: 5.25991e-06
        function: run
    - point:
        x: -9.93621
        y: 26.9713
        z: 4.54465e-06
        function: run_left_3_way_center
    - point:
        x: -9.88505
        y: 25.0284
        z: 3.11414e-06
        function: run
    - point:
        x: -10.0572
        y: 21.461
        z: 4.54465e-06
        function: run_go_3_way_left
    - point:
        x: -10.0159
        y: 10.1569
        z: 1.92205e-06
        function: run
    - point:
        x: -10.0295
        y: 5.56659
        z: -2.31069e-07
        function: run_go_3_way_left
    - point:
        x: -10.1404
        y: -1.42656
        z: 2.87572e-06
        function: run
    - point:
        x: -7.4907
        y: -4.1941
        z: -7.00555e-07
        function: run_left_corner_left
    - point:
        x: -2.95847
        y: -4.25945
        z: -3.32316e-06
        function: run
    - point:
        x: -0.274192
        y: -1.38079
        z: 7.29955e-07
        function: run_left_corner_left
    - point:
        x: -0.361026
        y: 2.42875
        z: -2.36949e-06
        function: run_go_3_way_right
    - point:
        x: -0.346048
        y: 5.49907
        z: 3.35256e-06
        function: run
    - point:
        x: -3.04405
        y: 7.70767
        z: 1.44522e-06
        function: run_left_3_way_left
    - point:
        x: -7.44071
        y: 7.76897
        z: 4.18702e-06
        function: run
