# global_costmap:
map_topic: map
global_frame: map
robot_base_frame: base_footprint
# robot_base_frame: base_link

# footprint: [[0.514, 0.395], [0.514, -0.395], [-0.314, -0.395], [-0.314, 0.395]]
# footprint: [[-0.205, -0.155], [-0.205, 0.155], [0.077, 0.155], [0.077, -0.155]]
# footprint: [ [0.20, 0.40], [0.20, -0.15], [-0.20, -0.15], [-0.20,0.40] ] 
# footprint: [ [-0.20, -0.15], [-0.20, 0.15], [0.20, 0.40],[0.20,-0.40] ] 
inflation_radius: 1.0 #0.5 
cost_scaling_factor: 1.0

update_frequency: 1
publish_frequency: 0.0
transform_tolerance: 2

static_map: true
rolling_window: false
always_send_full_costmap: false

plugins:
- {name: static_layer, type: "costmap_2d::StaticLayer" }
- {name: obstacles_layer, type: "costmap_2d::ObstacleLayer" }
- {name: inflation_layer,  type: "costmap_2d::InflationLayer" }   

    