# global_costmap:
map_topic: map
global_frame: map
robot_base_frame: base_footprint
# robot_base_frame: base_link

footprint: [[0.514, 0.395], [0.514, -0.395], [-0.314, -0.395], [-0.314, 0.395]]
inflation_radius: 0.5
cost_scaling_factor: 1.0

update_frequency: 1
publish_frequency: 1
transform_tolerance: 2

static_map: false
rolling_window: false
always_send_full_costmap: true

plugins:
- {name: static_layer, type: "costmap_2d::StaticLayer" }
- {name: obstacles_layer, type: "costmap_2d::ObstacleLayer" }
- {name: inflation_layer,  type: "costmap_2d::InflationLayer" }   

    