#local_costmap:
global_frame: odom
robot_base_frame: base_footprint
# robot_base_frame: base_link

# footprint: [[0.514, 0.395], [0.514, -0.395], [-0.314, -0.395], [-0.314, 0.395]]
# footprint: [ [0.20, 0.40], [0.20, -0.15], [-0.20, -0.15], [-0.20,0.40] ]
# footprint: [  [0.20, 0.40],[0.20,-0.40],[-0.20, -0.15], [-0.20, 0.15] ] 
resolution: 0.15
cost_scaling_factor: 10

inflation_radius: 0.5
update_frequency: 3.0
publish_frequency: 2.0
transform_tolerance: 1.0

static_map: false
rolling_window: true
width: 4.0
height: 4.0
resolution: 0.05

plugins:
- {name: obstacles_layer, type: "costmap_2d::ObstacleLayer" }
- {name: inflation_layer,  type: "costmap_2d::InflationLayer" }